=== SBoudrias/cocktails/packages/data/schemas/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./recipe.schema.json",
  "title": "Recipe",
  "description": "A cocktail recipe",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "name": { "type": "string" },
    "preparation": {
      "enum": [
        "built",
        "shaken",
        "stirred",
        "blended",
        "flash blended",
        "swizzled",
        "other"
      ]
    },
    "served_on": {
      "enum": ["big rock", "up", "crushed ice", "blended", "ice cubes"]
    },
    "glassware": {
      "enum": [
        "old fashioned",
        "collins",
        "highball",
        "snifter",
        "coupe",
        "martini",
        "nick & nora",
        "irish",
        "hurricane",
        "julep",
        "mule",
        "tiki",
        "punch",
        "flute",
        "footed pilsner",
        "goblet",
        "wine glass"
      ]
    },
    "servings": {
      "type": "integer",
      "minimum": 1,
      "description": "Default number of servings this recipe makes"
    },
    "ingredients": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "type": { "const": "syrup" },
              "brix": { "type": "number" },
              "technique": {
                "oneOf": [
                  { "$ref": "./technique.schema.json" },
                  {
                    "type": "array",
                    "items": { "$ref": "./technique.schema.json" }
                  }
                ]
              },
              "quantity": { "$ref": "./quantity.schema.json" }
            },
            "required": ["name", "type", "quantity"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "type": {
                "enum": [
                  "beer",
                  "bitter",
                  "emulsifier",
                  "category",
                  "fruit",
                  "juice",
                  "liqueur",
                  "puree",
                  "soda",
                  "spice",
                  "spirit",
                  "tincture",
                  "wine",
                  "other"
                ]
              },
              "brix": { "type": "number" },
              "technique": {
                "oneOf": [
                  { "$ref": "./technique.schema.json" },
                  {
                    "type": "array",
                    "items": { "$ref": "./technique.schema.json" }
                  }
                ]
              },
              "quantity": { "$ref": "./quantity.schema.json" }
            },
            "required": ["name", "type", "quantity"],
            "additionalProperties": false
          }
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "instructions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "attributions": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "relation": { "enum": ["recipe author", "adapted by"] },
              "source": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "relation": { "const": "bar" },
              "source": { "type": "string" },
              "location": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "relation": { "const": "book" },
              "source": { "type": "string" },
              "page": { "type": "number" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          }
        ]
      }
    },
    "refs": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "type": { "const": "youtube" },
              "videoId": { "type": "string" },
              "start": { "type": "number" }
            },
            "required": ["type", "videoId"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "book" },
              "title": { "type": "string" },
              "page": { "type": "number" }
            },
            "required": ["type", "title", "page"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "website" },
              "name": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["type", "name", "url"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "podcast" },
              "episodeTitle": { "type": "string" },
              "episodeLink": { "type": "string" }
            },
            "required": ["type", "episodeTitle"],
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "required": ["name", "ingredients", "preparation", "served_on", "glassware"],
  "additionalProperties": false
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/01_Fresh & Lively (Highball)/outrigger-nonalcoholic.json
{
  "$schema": "../../../../../schemas/recipe.schema.json",
  "name": "Outrigger (Nonalcoholic)",
  "preparation": "shaken",
  "served_on": "ice cubes",
  "glassware": "collins",
  "ingredients": [
    {
      "name": "Terra Spice Cola Extract",
      "type": "other",
      "quantity": {
        "amount": 1,
        "unit": "drop"
      }
    },
    {
      "name": "Acid phosphate",
      "type": "other",
      "quantity": {
        "amount": 1,
        "unit": "tsp"
      }
    },
    {
      "name": "Tamarind Demerara Syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "Pineapple juice",
      "type": "juice",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Seedlip Spice 94",
      "type": "spirit",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Seltzer",
      "type": "soda",
      "quantity": {
        "amount": 3,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Pour seltzer into a collins glass.",
    "Short shake remaining ingredients.",
    "Strain into the glass.",
    "Fill with ice cubes.",
    "Garnish with a lime wedge."
  ],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Matthew Belanger"
    },
    {
      "relation": "bar",
      "source": "Death & Co",
      "location": "New York, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 186
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/04_Boozy & Honest (Old-Fashioned)/monarch-julep.json
{
  "$schema": "../../../../../schemas/recipe.schema.json",
  "name": "Monarch Julep",
  "preparation": "built",
  "served_on": "crushed ice",
  "glassware": "julep",
  "ingredients": [
    {
      "name": "Honey syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "CioCiaro",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "G.E. Massenez Crème de Pêche",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Peach Street Peach Brandy",
      "type": "spirit",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Hidalgo Gobernador Oloroso",
      "type": "wine",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "J. Rieger Kansas City Whiskey",
      "type": "spirit",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    }
  ],
  "instructions": ["Garnish with a mint bouquet and peach slice. Serve with a straw."],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Tyson Buhler"
    },
    {
      "relation": "bar",
      "source": "Death & Co",
      "location": "New York, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 237
    }
  ]
}

=== SBoudrias/cocktails/src/data/recipes/book/smugglers-cove/arrack-punch.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Arrack punch",
  "preparation": "flash blended",
  "served_on": "crushed ice",
  "glassware": "punch",
  "ingredients": [
    {
      "name": "Lemon juice",
      "type": "juice",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    },
    {
      "name": "Demerara syrup",
      "brix": 66,
      "type": "syrup",
      "quantity": {
        "amount": 3,
        "unit": "oz"
      }
    },
    {
      "name": "Batavia Arrack van Oosten",
      "type": "spirit",
      "quantity": {
        "amount": 6,
        "unit": "oz"
      }
    },
    {
      "name": "Pot still lightly aged overproof rum",
      "type": "category",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    },
    {
      "name": "Carbonated Chai Tea",
      "type": "soda",
      "quantity": {
        "amount": 6,
        "unit": "oz"
      }
    }
  ],
  "refs": [
    {
      "type": "book",
      "page": 163,
      "title": "smugglers-cove"
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/05_Rich & Comforting (Flip)/clay-pigeons.json
{
  "$schema": "../../../../../schemas/recipe.schema.json",
  "name": "Clay Pigeons",
  "preparation": "built",
  "served_on": "up",
  "glassware": "irish",
  "ingredients": [
    {
      "name": "coffee",
      "type": "other",
      "technique": {
        "technique": "temperature",
        "method": "hot"
      },
      "quantity": {
        "amount": 3,
        "unit": "oz"
      }
    },
    {
      "name": "Giffard banane du Brésil",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Bénédictine",
      "type": "liqueur",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Leopold Bros. Maryland Rye",
      "type": "spirit",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Combine all the ingredients in an Irish coffee mug and stir to combine.",
    "Spoon some toasted oat cream on top of the drink and grate some nutmeg over the top."
  ],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Tyson Buhler"
    },
    {
      "relation": "bar",
      "source": "Death & Co",
      "location": "New York, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 275
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/tiki-modern-tropical-cocktails/04_Long Drinks and Coolers/magpie.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Magpie",
  "preparation": "shaken",
  "served_on": "crushed ice",
  "glassware": "collins",
  "ingredients": [
    {
      "name": "Papaya Syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "carrot juice",
      "type": "juice",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Campari",
      "type": "liqueur",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "Yaguara Cacha√ßa Branca",
      "type": "spirit",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Combine all ingredients in a shaker with cubed ice.",
    "Shake and strain into a chilled collins glass over pebbled ice.",
    "Garnish with edible flowers and a scored lime wedge."
  ],
  "refs": [
    {
      "type": "book",
      "title": "Easy Tiki",
      "page": 67
    }
  ]
}

=== SBoudrias/cocktails/src/data/recipes/book/smugglers-cove/tree-dots-and-a-dash.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Tree dots and a dash",
  "preparation": "flash blended",
  "served_on": "crushed ice",
  "glassware": "footed pilsner",
  "ingredients": [
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Orange juice",
      "type": "juice",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Honey syrup",
      "brix": 50,
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "John D. Taylor's Velvet Falernum",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "St-Elizabeth Allspice Dram",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Rhum agricole vieux",
      "type": "category",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Blended aged rum",
      "type": "category",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Angostura bitters",
      "type": "bitter",
      "quantity": {
        "amount": 1,
        "unit": "dash"
      }
    }
  ],
  "refs": [
    {
      "type": "book",
      "page": 43,
      "title": "smugglers-cove"
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/04_Boozy & Honest (Old-Fashioned)/noble-one.json
{
  "$schema": "../../../../../schemas/recipe.schema.json",
  "name": "Noble One",
  "preparation": "stirred",
  "served_on": "up",
  "glassware": "old fashioned",
  "ingredients": [
    {
      "name": "House Orange Bitters",
      "type": "bitter",
      "quantity": {
        "amount": 1,
        "unit": "dash"
      }
    },
    {
      "name": "Honey syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "tsp"
      }
    },
    {
      "name": "Rothman & Winter Orchard Apricot",
      "type": "liqueur",
      "quantity": {
        "amount": 1,
        "unit": "tsp"
      }
    },
    {
      "name": "Quinta do Infantado White Porto",
      "type": "wine",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Alvear Festival Pale Cream",
      "type": "wine",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    }
  ],
  "instructions": ["Express the lemon twist over the drink and discard."],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Javel Taft"
    },
    {
      "relation": "bar",
      "source": "Death & Co",
      "location": "New York, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 239
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/smugglers-cove/09_Eight Essential Exotic Elixirs/fog-cutter.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Fog cutter",
  "preparation": "flash blended",
  "served_on": "crushed ice",
  "glassware": "collins",
  "ingredients": [
    {
      "name": "Orgeat",
      "type": "category",
      "brix": 50,
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Lemon juice",
      "type": "juice",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Orange juice",
      "type": "juice",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Gin",
      "type": "category",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Pisco",
      "type": "category",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Blended Lightly-aged Rum",
      "type": "category",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    },
    {
      "name": "Sherry (Oloroso)",
      "type": "category",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    }
  ],
  "instructions": ["Float the sherry on top of the drink."],
  "attributions": [
    {
      "relation": "bar",
      "source": "Smuggler's Cove",
      "location": "San Francisco, CA"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "smugglers-cove",
      "page": 275
    }
  ]
}
