=== SBoudrias/cocktails/packages/data/schemas/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./recipe.schema.json",
  "title": "Recipe",
  "description": "A cocktail recipe",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "name": { "type": "string" },
    "preparation": {
      "enum": [
        "built",
        "shaken",
        "stirred",
        "blended",
        "flash blended",
        "swizzled",
        "other"
      ]
    },
    "served_on": {
      "enum": ["big rock", "up", "crushed ice", "blended", "ice cubes"]
    },
    "glassware": {
      "enum": [
        "old fashioned",
        "collins",
        "highball",
        "snifter",
        "coupe",
        "martini",
        "nick & nora",
        "irish",
        "hurricane",
        "julep",
        "mule",
        "tiki",
        "punch",
        "flute",
        "footed pilsner",
        "goblet",
        "wine glass"
      ]
    },
    "servings": {
      "type": "integer",
      "minimum": 1,
      "description": "Default number of servings this recipe makes"
    },
    "ingredients": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "type": { "const": "syrup" },
              "brix": { "type": "number" },
              "technique": {
                "oneOf": [
                  { "$ref": "./technique.schema.json" },
                  {
                    "type": "array",
                    "items": { "$ref": "./technique.schema.json" }
                  }
                ]
              },
              "quantity": { "$ref": "./quantity.schema.json" }
            },
            "required": ["name", "type", "quantity"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "type": {
                "enum": [
                  "beer",
                  "bitter",
                  "emulsifier",
                  "category",
                  "fruit",
                  "juice",
                  "liqueur",
                  "puree",
                  "soda",
                  "spice",
                  "spirit",
                  "tincture",
                  "wine",
                  "other"
                ]
              },
              "brix": { "type": "number" },
              "technique": {
                "oneOf": [
                  { "$ref": "./technique.schema.json" },
                  {
                    "type": "array",
                    "items": { "$ref": "./technique.schema.json" }
                  }
                ]
              },
              "quantity": { "$ref": "./quantity.schema.json" }
            },
            "required": ["name", "type", "quantity"],
            "additionalProperties": false
          }
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "instructions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "attributions": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "relation": { "enum": ["recipe author", "adapted by"] },
              "source": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "relation": { "const": "bar" },
              "source": { "type": "string" },
              "location": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "relation": { "const": "book" },
              "source": { "type": "string" },
              "page": { "type": "number" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          }
        ]
      }
    },
    "refs": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "type": { "const": "youtube" },
              "videoId": { "type": "string" },
              "start": { "type": "number" }
            },
            "required": ["type", "videoId"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "book" },
              "title": { "type": "string" },
              "page": { "type": "number" }
            },
            "required": ["type", "title", "page"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "website" },
              "name": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["type", "name", "url"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "podcast" },
              "episodeTitle": { "type": "string" },
              "episodeLink": { "type": "string" }
            },
            "required": ["type", "episodeTitle"],
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "required": ["name", "ingredients", "preparation", "served_on", "glassware"],
  "additionalProperties": false
}

=== SBoudrias/cocktails/src/data/recipes/youtube-channel/anders-erickson/tipperary.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Tipperary",
  "preparation": "stirred",
  "served_on": "up",
  "glassware": "martini",
  "ingredients": [
    {
      "name": "Angostura bitters",
      "type": "bitter",
      "quantity": {
        "amount": 2,
        "unit": "dash"
      }
    },
    {
      "name": "Green Chartreuse",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Dolin Sweet Vermouth de Chamb√©ry",
      "type": "liqueur",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Redbreast 12 year Irish whiskey",
      "type": "spirit",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Stir all ingredients with ice.",
    "Strain into a chilled martini glass.",
    "Express lemon oil over the drink and discard the peel."
  ],
  "refs": [
    {
      "type": "youtube",
      "videoId": "2zQBXxC7ma8",
      "start": 197
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/minimalist-tiki/01_The New Tiki Vanguard/pacific-theatre.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Pacific Theatre",
  "preparation": "shaken",
  "served_on": "up",
  "glassware": "nick & nora",
  "ingredients": [
    {
      "name": "Absinthe",
      "type": "category",
      "quantity": {
        "amount": 1,
        "unit": "dash"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Pineapple juice",
      "type": "juice",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Passion fruit syrup",
      "type": "category",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Pandan Syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Hampden Estate Rum Fire",
      "type": "spirit",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "The Real McCoy 3 Year",
      "type": "spirit",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Build ingredients in shaker.",
    "Shake with ice, strain into a chilled Nick & Nora or coupe glass.",
    "Spritz with absinthe.",
    "Garnish with an orchid."
  ],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Brian Maxwell"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "Minimalist Tiki",
      "page": 144
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/youtube-channel/make-and-drink/pink-squirrel.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Pink Squirrel",
  "preparation": "shaken",
  "served_on": "up",
  "glassware": "coupe",
  "ingredients": [
    {
      "name": "Sweet cream",
      "type": "other",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Crème de Cacao",
      "type": "category",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Tempus Fugit Crème de Noyaux",
      "type": "liqueur",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    }
  ],
  "attributions": [
    {
      "relation": "bar",
      "source": "Bryant's Cocktail Lounge",
      "location": "Milwaukee"
    }
  ],
  "refs": [
    {
      "type": "youtube",
      "videoId": "tazH988uMO4"
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/05_Elegant & Graceful (Martini)/negroni-standing-room.json
{
  "$schema": "../../../../../schemas/recipe.schema.json",
  "name": "Negroni Standing Room",
  "preparation": "stirred",
  "served_on": "big rock",
  "glassware": "old fashioned",
  "ingredients": [
    {
      "name": "cucumber juice",
      "type": "juice",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Rhine Hall Mango Brandy",
      "type": "spirit",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Cimarron Blanco Tequila",
      "type": "spirit",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Aperol",
      "type": "liqueur",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Dolin Blanc Vermouth de Chambéry",
      "type": "wine",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Stir all the ingredients over ice, then strain into a double old-fashioned glass over 1 large ice cube. Garnish with the coriander flower."
  ],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Tyson Buhler"
    },
    {
      "relation": "bar",
      "source": "Death & Co"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 259
    }
  ]
}

=== SBoudrias/cocktails/src/data/recipes/book/tropical-standard/kingston-zing.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Kingston Zing",
  "preparation": "shaken",
  "served_on": "ice cubes",
  "glassware": "highball",
  "ingredients": [
    {
      "name": "Saline",
      "type": "other",
      "quantity": {
        "amount": 5,
        "unit": "drop"
      }
    },
    {
      "name": "Bittermens Hopped Grapefruit Bitters",
      "type": "bitter",
      "quantity": {
        "amount": 6,
        "unit": "drop"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.375,
        "unit": "oz"
      }
    },
    {
      "name": "Grapefruit punch syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Wray & Nephew white overproof",
      "type": "spirit",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Seltzer",
      "type": "soda",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "tropical-standard",
      "page": 87
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/minimalist-tiki/03_The Next Wave/pagan-breakfast.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Pagan Breakfast",
  "preparation": "shaken",
  "served_on": "up",
  "glassware": "nick & nora",
  "ingredients": [
    {
      "name": "Absinthe",
      "type": "category",
      "quantity": {
        "amount": 2,
        "unit": "dash"
      }
    },
    {
      "name": "Simple syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "The Real McCoy 3 Year",
      "type": "spirit",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Build ingredients in shaker.",
    "Shake well with cubed ice, strain into a chilled Nick & Nora or coupe glass."
  ],
  "attributions": [
    {
      "relation": "bar",
      "source": "Pagan Idol",
      "location": "San Francisco, CA"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "Minimalist Tiki",
      "page": 248
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/04_Boozy & Honest (Old-Fashioned)/the-manticore.json
{
  "$schema": "../../../../../schemas/recipe.schema.json",
  "name": "The Manticore",
  "preparation": "stirred",
  "served_on": "big rock",
  "glassware": "old fashioned",
  "ingredients": [
    {
      "name": "Peychaud's bitters",
      "type": "bitter",
      "quantity": {
        "amount": 1.5,
        "unit": "dash"
      }
    },
    {
      "name": "Cinnamon syrup",
      "type": "syrup",
      "quantity": {
        "amount": 1,
        "unit": "tsp"
      }
    },
    {
      "name": "Giffard Menthe-Pastille",
      "type": "liqueur",
      "quantity": {
        "amount": 1,
        "unit": "tsp"
      }
    },
    {
      "name": "John D. Taylor's Velvet Falernum",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Beefeater London Dry Gin",
      "type": "spirit",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "instructions": ["Express the lemon twist over the drink, then place it in the drink."],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Scott Teague"
    },
    {
      "relation": "bar",
      "source": "Death & Co",
      "location": "New York, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 237
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/tropical-standard/10_Expansion - Savory/jump-up-jamaica.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Jump Up, Jamaica",
  "preparation": "shaken",
  "served_on": "ice cubes",
  "glassware": "wine glass",
  "ingredients": [
    {
      "name": "Saline",
      "type": "other",
      "quantity": {
        "amount": 5,
        "unit": "drop"
      }
    },
    {
      "name": "Angostura bitters",
      "type": "bitter",
      "quantity": {
        "amount": 2,
        "unit": "dash"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Grapefruit punch syrup",
      "type": "syrup",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Wray & Nephew white overproof",
      "type": "spirit",
      "technique": {
        "technique": "infusion",
        "agent": "serrano pepper"
      },
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Coruba",
      "type": "spirit",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Rum",
      "type": "category",
      "technique": {
        "technique": "infusion",
        "agent": "sorrel"
      },
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Seltzer",
      "type": "soda",
      "quantity": {
        "amount": 3,
        "unit": "oz"
      }
    }
  ],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Garret Richard"
    },
    {
      "relation": "bar",
      "source": "Sunken Harbor Club",
      "location": "Brooklyn, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "tropical-standard",
      "page": 167
    }
  ]
}
