=== SBoudrias/cocktails/packages/data/schemas/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./recipe.schema.json",
  "title": "Recipe",
  "description": "A cocktail recipe",
  "type": "object",
  "properties": {
    "$schema": { "type": "string" },
    "name": { "type": "string" },
    "preparation": {
      "enum": [
        "built",
        "shaken",
        "stirred",
        "blended",
        "flash blended",
        "swizzled",
        "other"
      ]
    },
    "served_on": {
      "enum": ["big rock", "up", "crushed ice", "blended", "ice cubes"]
    },
    "glassware": {
      "enum": [
        "old fashioned",
        "collins",
        "highball",
        "snifter",
        "coupe",
        "martini",
        "nick & nora",
        "irish",
        "hurricane",
        "julep",
        "mule",
        "tiki",
        "punch",
        "flute",
        "footed pilsner",
        "goblet",
        "wine glass"
      ]
    },
    "servings": {
      "type": "integer",
      "minimum": 1,
      "description": "Default number of servings this recipe makes"
    },
    "ingredients": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "type": { "const": "syrup" },
              "brix": { "type": "number" },
              "technique": {
                "oneOf": [
                  { "$ref": "./technique.schema.json" },
                  {
                    "type": "array",
                    "items": { "$ref": "./technique.schema.json" }
                  }
                ]
              },
              "quantity": { "$ref": "./quantity.schema.json" }
            },
            "required": ["name", "type", "quantity"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "type": {
                "enum": [
                  "beer",
                  "bitter",
                  "emulsifier",
                  "category",
                  "fruit",
                  "juice",
                  "liqueur",
                  "puree",
                  "soda",
                  "spice",
                  "spirit",
                  "tincture",
                  "wine",
                  "other"
                ]
              },
              "brix": { "type": "number" },
              "technique": {
                "oneOf": [
                  { "$ref": "./technique.schema.json" },
                  {
                    "type": "array",
                    "items": { "$ref": "./technique.schema.json" }
                  }
                ]
              },
              "quantity": { "$ref": "./quantity.schema.json" }
            },
            "required": ["name", "type", "quantity"],
            "additionalProperties": false
          }
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "instructions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "attributions": {
      "type": "array",
      "items": {
        "type": "object",
        "oneOf": [
          {
            "type": "object",
            "properties": {
              "relation": { "enum": ["recipe author", "adapted by"] },
              "source": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "relation": { "const": "bar" },
              "source": { "type": "string" },
              "location": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "relation": { "const": "book" },
              "source": { "type": "string" },
              "page": { "type": "number" },
              "url": { "type": "string" }
            },
            "required": ["source", "relation"],
            "additionalProperties": false
          }
        ]
      }
    },
    "refs": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "type": { "const": "youtube" },
              "videoId": { "type": "string" },
              "start": { "type": "number" }
            },
            "required": ["type", "videoId"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "book" },
              "title": { "type": "string" },
              "page": { "type": "number" }
            },
            "required": ["type", "title", "page"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "website" },
              "name": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["type", "name", "url"],
            "additionalProperties": false
          },
          {
            "type": "object",
            "properties": {
              "type": { "const": "podcast" },
              "episodeTitle": { "type": "string" },
              "episodeLink": { "type": "string" }
            },
            "required": ["type", "episodeTitle"],
            "additionalProperties": false
          }
        ]
      }
    }
  },
  "required": ["name", "ingredients", "preparation", "served_on", "glassware"],
  "additionalProperties": false
}

=== SBoudrias/cocktails/src/data/recipes/book/smugglers-cove/navy-grog.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Navy grog",
  "preparation": "flash blended",
  "served_on": "crushed ice",
  "glassware": "old fashioned",
  "ingredients": [
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "Grapefruit juice",
      "type": "juice",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "Demerara syrup",
      "brix": 66,
      "type": "syrup",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "St. Elizabeth allspice Dram",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Pot still lightly aged overproof rum",
      "type": "category",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Blended lightly aged rum",
      "type": "category",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Column still aged rum",
      "type": "category",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    }
  ],
  "refs": [
    {
      "type": "book",
      "page": 271,
      "title": "smugglers-cove"
    },
    {
      "type": "youtube",
      "videoId": "ZtRwS65Xz_Q"
    }
  ],
  "attributions": [
    {
      "relation": "bar",
      "source": "Smuggler's Cove",
      "location": "San Francisco, CA"
    }
  ]
}

=== SBoudrias/cocktails/src/data/recipes/youtube-channel/anders-erickson/sazerac.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Sazerac",
  "preparation": "stirred",
  "served_on": "up",
  "glassware": "coupe",
  "ingredients": [
    {
      "name": "Sazerac Straight Rye Whiskey",
      "type": "spirit",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    },
    {
      "name": "Maison Rouge VSOP Cognac",
      "type": "spirit",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "simple syrup",
      "type": "syrup",
      "brix": 60,
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "Peychaud's Bitters",
      "type": "bitter",
      "quantity": {
        "amount": 3,
        "unit": "dash"
      }
    },
    {
      "name": "Angostura Bitters",
      "type": "bitter",
      "quantity": {
        "amount": 1,
        "unit": "dash"
      }
    },
    {
      "name": "Nouvelle Orleans Absinthe Superieure",
      "type": "spirit",
      "quantity": {
        "amount": 1,
        "unit": "spray"
      }
    }
  ],
  "instructions": [
    "Rinse a chilled old fashioned glass with absinthe and discard the excess.",
    "Stir the remaining ingredients with ice.",
    "Strain into the prepared glass.",
    "Garnish with lemon zest."
  ],
  "refs": [
    {
      "type": "youtube",
      "videoId": "dJ-sAEzw9Jc"
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/smugglers-cove/06_Rum Through the Ages/arrack-punch.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Arrack punch",
  "preparation": "flash blended",
  "served_on": "crushed ice",
  "glassware": "punch",
  "ingredients": [
    {
      "name": "Lemon juice",
      "type": "juice",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    },
    {
      "name": "Demerara syrup",
      "type": "syrup",
      "brix": 66,
      "quantity": {
        "amount": 3,
        "unit": "oz"
      }
    },
    {
      "name": "Pot still lightly aged overproof rum",
      "type": "category",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    },
    {
      "name": "Batavia Arrack van Oosten",
      "type": "spirit",
      "quantity": {
        "amount": 6,
        "unit": "oz"
      }
    },
    {
      "name": "Carbonated chai tea",
      "type": "soda",
      "quantity": {
        "amount": 6,
        "unit": "oz"
      }
    }
  ],
  "attributions": [
    {
      "relation": "bar",
      "source": "Smuggler's Cove",
      "location": "San Francisco, CA"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "smugglers-cove",
      "page": 163
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/03_Bright & Confident (Sidecar)/heart-throb.json
{
  "$schema": "../../../../../schemas/recipe.schema.json",
  "name": "Heart Throb",
  "preparation": "shaken",
  "served_on": "up",
  "glassware": "coupe",
  "ingredients": [
    {
      "name": "Cinnamon syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Lime juice",
      "type": "juice",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "Giffard crème de pamplemousse rose",
      "type": "liqueur",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Flor de Caña 4 year",
      "type": "spirit",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Shake all the ingredients with ice, then double strain into a chilled coupe."
  ],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Scott Teague"
    },
    {
      "relation": "bar",
      "source": "Death & Co",
      "location": "New York, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 219
    }
  ]
}

=== SBoudrias/cocktails/src/data/recipes/book/tiki-modern-tropical-cocktails/buccaneers-bounty.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Buccaneer's Bounty",
  "ingredients": [
    {
      "name": "Spiced Rum",
      "type": "category",
      "quantity": {
        "amount": 8.5,
        "unit": "oz"
      }
    },
    {
      "name": "Rittenhouse Rye",
      "type": "spirit",
      "quantity": {
        "amount": 4.25,
        "unit": "oz"
      }
    },
    {
      "name": "cinnamon syrup",
      "type": "syrup",
      "quantity": {
        "amount": 3.33,
        "unit": "oz"
      }
    },
    {
      "name": "soursop juice",
      "type": "juice",
      "quantity": {
        "amount": 4.25,
        "unit": "oz"
      }
    },
    {
      "name": "lime juice",
      "type": "juice",
      "quantity": {
        "amount": 4.25,
        "unit": "oz"
      }
    },
    {
      "name": "Angostura bitters",
      "type": "bitter",
      "quantity": {
        "amount": 1.5,
        "unit": "oz"
      }
    }
  ],
  "preparation": "built",
  "served_on": "ice cubes",
  "glassware": "punch",
  "servings": 6,
  "instructions": [
    "Combine all ingredients in a nonreactive container and stir to mix",
    "Decant over ice into a Tiki bowl or serving vessel of your choice",
    "Serve with straws and garnish with citrus wheels and edible flowers"
  ],
  "refs": [
    {
      "type": "book",
      "title": "Tiki: Modern Tropical Cocktails",
      "page": 141
    }
  ]
}

=== SBoudrias/cocktails/src/data/recipes/book/tropical-standard/our-man-in-havana.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Our Man in Havana",
  "preparation": "stirred",
  "served_on": "ice cubes",
  "glassware": "nick & nora",
  "ingredients": [
    {
      "name": "Saline",
      "type": "other",
      "quantity": {
        "amount": 3,
        "unit": "drop"
      }
    },
    {
      "name": "Orange bitters",
      "type": "category",
      "quantity": {
        "amount": 1,
        "unit": "dash"
      }
    },
    {
      "name": "Angostura bitters",
      "type": "bitter",
      "quantity": {
        "amount": 1,
        "unit": "dash"
      }
    },
    {
      "name": "orgeat",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "tsp"
      }
    },
    {
      "name": "Pierre Ferrand Dry Cura√ßao",
      "type": "liqueur",
      "quantity": {
        "amount": 1,
        "unit": "tsp"
      }
    },
    {
      "name": "Barbancourt 5 Star",
      "type": "spirit",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Byrrh Grand Quinquina",
      "type": "liqueur",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "tropical-standard",
      "page": 138
    }
  ]
}

=== SBoudrias/cocktails/packages/data/data/recipes/book/death-co-welcome-home/01_Fresh & Lively (Highball)/ursa-major.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Ursa Major",
  "preparation": "built",
  "served_on": "ice cubes",
  "glassware": "highball",
  "ingredients": [
    {
      "name": "Lactart",
      "type": "other",
      "quantity": {
        "amount": 0.5,
        "unit": "tsp"
      }
    },
    {
      "name": "Vanilla syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.5,
        "unit": "oz"
      }
    },
    {
      "name": "Rare Tea Company Genmaicha",
      "type": "other",
      "quantity": {
        "amount": 4,
        "unit": "oz"
      }
    },
    {
      "name": "Marie Brizard Crème de Cacao Blanc",
      "type": "liqueur",
      "quantity": {
        "amount": 0.25,
        "unit": "oz"
      }
    },
    {
      "name": "St. George California Rice Shochu",
      "type": "spirit",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "instructions": [
    "Chill all ingredients.",
    "Combine in a carbonating bottle, charge with CO₂, and gently shake to dissolve CO₂.",
    "Refrigerate at least 20 minutes (preferably 12 hours).",
    "Pour into a highball glass and fill with ice cubes.",
    "Express a lemon twist over the drink, then place it in the drink."
  ],
  "attributions": [
    {
      "relation": "recipe author",
      "source": "Matthew Belanger"
    },
    {
      "relation": "bar",
      "source": "Death & Co",
      "location": "New York, NY"
    }
  ],
  "refs": [
    {
      "type": "book",
      "title": "death-co-welcome-home",
      "page": 190
    }
  ]
}

=== SBoudrias/cocktails/src/data/recipes/youtube-channel/make-and-drink/marys-daiquiri.json
{
  "$schema": "../../../../schemas/recipe.schema.json",
  "name": "Mary's Daiquiri",
  "preparation": "flash blended",
  "served_on": "crushed ice",
  "glassware": "old fashioned",
  "ingredients": [
    {
      "name": "Dry Reisling syrup",
      "type": "syrup",
      "quantity": {
        "amount": 0.75,
        "unit": "oz"
      }
    },
    {
      "name": "lime juice",
      "type": "juice",
      "quantity": {
        "amount": 1,
        "unit": "oz"
      }
    },
    {
      "name": "Barbancourt 110 Haitian Proof",
      "type": "spirit",
      "quantity": {
        "amount": 2,
        "unit": "oz"
      }
    }
  ],
  "attributions": [
    {
      "source": "Doc Parks",
      "relation": "recipe author"
    }
  ],
  "refs": [
    {
      "type": "youtube",
      "videoId": "h5eBFKwaxeg"
    }
  ]
}
